services:
  postgis:
    image: postgis/postgis:13-3.4
    restart: on-failure
    ports:
      - 5432:5432
    volumes:
      - ./database/db_init.sh:/docker-entrypoint-initdb.d/db_init.sh
      - ./database/sql/:/tmp/sql/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    networks:
      - backend
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: on-failure
    ports:
      - "8001:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=1234
    networks:
      - frontend
      - backend
    depends_on:
      - postgis

  watershedbc:
    image: watershedbc
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:3838
    volumes:
      - ./:/watershed-app
    environment:
      - aw_dbname=postgres
      - aw_host=postgis
      - aw_port=5432
      - aw_user=postgres
      - aw_password=postgres
    networks:
      - frontend
      - backend
    depends_on:
      - postgis

networks:
  frontend:
  backend:   
