services:
  postgis:
    image: postgis/postgis
    restart: on-failure
    ports:
      - 5432:5432
    volumes:
      - ./:/tmp
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=public
    networks:
      - backend
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: on-failure
    ports:
      - "8001:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: 1234
    networks:
      - frontend
      - backend
    depends_on:
      - postgis

  watershedbc:
    image: watershedbc
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:3838
    volumes:
      - ./:/watershed-app
    environment:
      - aw_dbname=public
      - aw_host=postgis
      - aw_port=5432
      - aw_user=postgres
      - aw_password=postgres
    networks:
      - frontend
      - backend
    depends_on:
      - postgis

networks:
  frontend:
  backend:   
