-- USER CREATION

-- READONLY_USER
DROP ROLE IF EXISTS readonly_user;

CREATE ROLE readonly_user WITH
  LOGIN
  NOSUPERUSER
  NOINHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION
  NOBYPASSRLS;

DROP ROLE IF EXISTS readonly_user_shiny;

-- READONLY_USER_SHINY
CREATE ROLE readonly_user_shiny WITH
  LOGIN
  NOSUPERUSER
  NOINHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION
  NOBYPASSRLS;

ALTER ROLE readonly_user_shiny IN DATABASE postgres SET transaction_read_only TO 'true';

-- SHINY
DROP ROLE IF EXISTS shiny;

CREATE ROLE shiny WITH
  LOGIN
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION
  NOBYPASSRLS;

-- GRANT readaccess TO shiny;
